// as 服务, 即是 a3 的 grpc 服务

// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file api/ts/v1/ts.proto (package api.ts.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PingRequest, PingResponse, QueryPhraseListRequest, QueryPhraseListResponse, UpsertPhraseListRequest, UpsertPhraseListResponse } from "./ts_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ----------------------------------------------------------------------------------------------------------------------
 * ----------------------------------------------------------------------------------------------------------------------
 *
 * @generated from service api.ts.v1.TService
 */
export const TService = {
  typeName: "api.ts.v1.TService",
  methods: {
    /**
     * ----------------------------------------------------------------------------------------------------------------------
     *
     * @generated from rpc api.ts.v1.TService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 账号
     *
     * ui
     *
     * @generated from rpc api.ts.v1.TService.QueryPhraseList
     */
    queryPhraseList: {
      name: "QueryPhraseList",
      I: QueryPhraseListRequest,
      O: QueryPhraseListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ui
     *
     * @generated from rpc api.ts.v1.TService.UpsertPhraseList
     */
    upsertPhraseList: {
      name: "UpsertPhraseList",
      I: UpsertPhraseListRequest,
      O: UpsertPhraseListResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

