export enum ActionStore {
    Default = "",
    DeleteApk = "deleteApkRow",
    DeleteApks = "deleteApkRows",
    DeleteApkversion = "deleteApkversionRow",
    DeleteFirmware = "deleteFirmwareRow",
    DeletePermission = "deletePermission",
    DeleteFirmwares = "deleteFirmwareRows",
    DeleteFirmwareversion = "deleteFirmwareversionRow",
    DeleteRole = "deleteRoleRow",
    DeleteUser = "deleteUserRow",
    DeleteAccount = "deleteAccountRow",
    Deleteterminal = "deleteTerminalRow",
    DeleteAdd = "deleteAddRow",
    DeleteBackground = "deleteBackground",
    Deletenotification = "deleteNotification",
    DeleteTvnotification = "deleteTvNotification",

    ResetUserPwd = "resetUserpwd",
    DeleteDeskImage = "deleteDeskImage",
    DeleteTVApk = "deletetvapk",
    DeleteTVApks = "deletetvapks",
    DeleteTVAccount = "deletetvaccount",
    DeleteTVFirmware = "deletetvfirmware",
    DeleteTVFirmwarrversion = "deletetvfirmwareversion",
    DeleteTVApkversion = "deletetvapkversion",
    DeleteTVBackground = "deletetvbackground",
    DeleteTVAdd = "deletetvadd",
    DeleteTVDeskImage = "deletetvdeskImage",
    DeleteTVMXSource = "deletetvmxsource",
    DeleteTVMXCombo = "deletetvmXCombo",
    DeleteTVMAccount = "deletetvmAccount",
    //     wst
    DeleteApps = "deleteApps",
    DeleteAppsversion = "deleteAppsversion",
    DeleteCategories = "deleteCategories",
    DeletePricePlans = "deletePricePlans",
    //     server
    DeleteServer = "deleteServer",
    DeleteTVServer = "deleteTvServer",
    DeleteAppUser = "deleteAppUser",
    DeleteTVMXStream = "DeleteTVMXStream",
    DeleteXCAccount = "DeleteXCAccount",
    DeleteEPG = "DeleteEPG",
    DeleteTVterminal = "deleteTVterminal",
    DeleteAddress = "deleteAddress",
    DeleteMainClass = "deleteMainClass",
    DeleteSubClass = "deleteSubClass",
    DeleteChannel = "deleteChannel",
    DeleteLink = "deleteLink",
    DeleteAgreement = "deleteAgreement",
    DeleteClassInfo = "deleteClassInfo",
    DeleteRecommend = "deleteRecommend",
    DeleteResource = "deleteResource",
    DeleteVideo = "deleteVideo",
    DeletePlayback = "deletePlayback",
    DeleteAppBanner = "deleteAppbanner",
    //
    DeleteVideoForDistributor = "deleteVideoForDistributor",
    DeleteVodClass = "DeleteVodClass",
    DeleteVod = "DeleteVod",
    DeleteVodLink = "DeleteVodLink",
    DeleteApkCategory = "DeleteApkCategory",
    DeleteDistributorDetail = "DeleteDistributorDetail",
    DeleteRecommendApk = "DeleteRecommendApk",
    DeleteVodAccount = "DeleteVodAccount",
    DeleteVodLinkAccount = "DeleteVodLinkAccount",
    DeleteVodDeskTop = "DeleteVodDeskTop",
    TVDeletenotification = "TVDeletenotification",
    DeleteOTTAppBanner = "DeleteOTTAppBanner",

//
    DeleteMowoClass = "DeleteMowoClass",
    DeleteClassResource = "DeleteClassResource",
    DeleteClassData = "DeleteClassData",
    DeleteVodBanner = "DeleteVodBanner",

//
    DeleteVodType = "DeleteVodType",
    DeleteVodTypeItem = "DeleteVodTypeItem"


}
