// as 服务, 即是 a3 的 grpc 服务

// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file api/qs/v1/qs.proto (package api.qs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CountTestingByFilterRequest, CountTestingByFilterResponse, CountTestingRequest, CountTestingResponse, QueryTestingListByFilterRequest, QueryTestingListByFilterResponse, QueryTestingListRequest, QueryTestingListResponse, UpsertTestingRecordListRequest, UpsertTestingRecordListResponse } from "./qs_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.qs.v1.QService
 */
export const QService = {
  typeName: "api.qs.v1.QService",
  methods: {
    /**
     *  rpc Ping(PingRequest) returns (PingResponse);
     * ----------------------------------------------------------------------------------------------------------------------
     * 以下是管理界面使用的
     * ----------------------------------------------------------------------------------------------------------------------
     *
     * @generated from rpc api.qs.v1.QService.UpsertTestingRecordList
     */
    upsertTestingRecordList: {
      name: "UpsertTestingRecordList",
      I: UpsertTestingRecordListRequest,
      O: UpsertTestingRecordListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 
     *
     * @generated from rpc api.qs.v1.QService.CountTesting
     */
    countTesting: {
      name: "CountTesting",
      I: CountTestingRequest,
      O: CountTestingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 
     *
     * @generated from rpc api.qs.v1.QService.QueryTestingList
     */
    queryTestingList: {
      name: "QueryTestingList",
      I: QueryTestingListRequest,
      O: QueryTestingListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.qs.v1.QService.CountTestingByFilter
     */
    countTestingByFilter: {
      name: "CountTestingByFilter",
      I: CountTestingByFilterRequest,
      O: CountTestingByFilterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ----------------------------------------------------------------------------------------------------------------------
     *  web 管理界面使用的接口, 到这里结束
     * ----------------------------------------------------------------------------------------------------------------------
     *
     * @generated from rpc api.qs.v1.QService.QueryTestingListByFilter
     */
    queryTestingListByFilter: {
      name: "QueryTestingListByFilter",
      I: QueryTestingListByFilterRequest,
      O: QueryTestingListByFilterResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

