// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file api/ac/v1/acs.proto (package api.ac.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryDeviceByMacChipRequest, QueryDeviceByMacChipResponse, SignUpRequest, SignUpResponse } from "./acs_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.ac.v1.ACService
 */
export const ACService = {
  typeName: "api.ac.v1.ACService",
  methods: {
    /**
     * ----------------------------------------------------------------------------------------------------------------------
     * 以下由 acnv 调用
     *
     * @generated from rpc api.ac.v1.ACService.SignUp
     */
    signUp: {
      name: "SignUp",
      I: SignUpRequest,
      O: SignUpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ac.v1.ACService.QueryDeviceByMacChip
     */
    queryDeviceByMacChip: {
      name: "QueryDeviceByMacChip",
      I: QueryDeviceByMacChipRequest,
      O: QueryDeviceByMacChipResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

