// a3 服务采用的模型, 清除所有不必要字段

// @generated by protoc-gen-es v1.3.0 with parameter "target=ts"
// @generated from file api/tv_fs/v1/fm.proto (package api.tv_fs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum api.tv_fs.v1.MlrStatus
 */
export enum MlrStatus {
  /**
   * 不使用的状态
   *
   * @generated from enum value: MLR_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * meta 入库成功
   *
   * @generated from enum value: MLR_STATUS_STORAGE = 1;
   */
  STORAGE = 1,

  /**
   * 等待上传
   *
   * @generated from enum value: MLR_STATUS_UPLOAD = 2;
   */
  UPLOAD = 2,

  /**
   * 上传成功
   *
   * @generated from enum value: MLR_STATUS_MLR_SUCCESS = 3;
   */
  MLR_SUCCESS = 3,

  /**
   * 在线, 可以下载
   *
   * @generated from enum value: MLR_STATUS_ONLINE = 4;
   */
  ONLINE = 4,

  /**
   * 文件存在, 但不能下载, 这是保留字段
   *
   * @generated from enum value: MLR_STATUS_OFFLINE = 6;
   */
  OFFLINE = 6,

  /**
   * 文件已经删除
   *
   * @generated from enum value: MLR_STATUS_DELETED = 7;
   */
  DELETED = 7,

  /**
   * 不再支持
   *
   * @generated from enum value: MLR_STATUS_DISABLE = 8;
   */
  DISABLE = 8,

  /**
   * 强制升级
   *
   * @generated from enum value: MLR_STATUS_FORCE_UPGRADE = 9;
   */
  FORCE_UPGRADE = 9,

  /**
   * 强制静默升级
   *
   * @generated from enum value: MLR_STATUS_FORCE_SILENT_UPDATE = 10;
   */
  FORCE_SILENT_UPDATE = 10,

  /**
   * 强制本地删除, 这里指 android 内删除
   *
   * @generated from enum value: MLR_STATUS_FORCE_LOCAL_DELETE = 11;
   */
  FORCE_LOCAL_DELETE = 11,
}
// Retrieve enum metadata with: proto3.getEnumType(MlrStatus)
proto3.util.setEnumType(MlrStatus, "api.tv_fs.v1.MlrStatus", [
  { no: 0, name: "MLR_STATUS_UNSPECIFIED" },
  { no: 1, name: "MLR_STATUS_STORAGE" },
  { no: 2, name: "MLR_STATUS_UPLOAD" },
  { no: 3, name: "MLR_STATUS_MLR_SUCCESS" },
  { no: 4, name: "MLR_STATUS_ONLINE" },
  { no: 6, name: "MLR_STATUS_OFFLINE" },
  { no: 7, name: "MLR_STATUS_DELETED" },
  { no: 8, name: "MLR_STATUS_DISABLE" },
  { no: 9, name: "MLR_STATUS_FORCE_UPGRADE" },
  { no: 10, name: "MLR_STATUS_FORCE_SILENT_UPDATE" },
  { no: 11, name: "MLR_STATUS_FORCE_LOCAL_DELETE" },
]);

/**
 * q 接口 post 参数
 *
 * @generated from message api.tv_fs.v1.DownloadFilter
 */
export class DownloadFilter extends Message<DownloadFilter> {
  /**
   * @generated from field: string version = 1;
   */
  version = "";

  /**
   * @generated from field: int32 last = 2;
   */
  last = 0;

  /**
   * @generated from field: api.tv_fs.v1.MlrStatus status = 3;
   */
  status = MlrStatus.UNSPECIFIED;

  /**
   * @generated from field: string apk_type = 4;
   */
  apkType = "";

  /**
   * @generated from field: string media_type = 5;
   */
  mediaType = "";

  /**
   * apk 支持的硬件
   *
   * @generated from field: string hardware = 6;
   */
  hardware = "";

  constructor(data?: PartialMessage<DownloadFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.DownloadFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "last", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "status", kind: "enum", T: proto3.getEnumType(MlrStatus) },
    { no: 4, name: "apk_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "media_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "hardware", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadFilter {
    return new DownloadFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadFilter {
    return new DownloadFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadFilter {
    return new DownloadFilter().fromJsonString(jsonString, options);
  }

  static equals(a: DownloadFilter | PlainMessage<DownloadFilter> | undefined, b: DownloadFilter | PlainMessage<DownloadFilter> | undefined): boolean {
    return proto3.util.equals(DownloadFilter, a, b);
  }
}

/**
 * --------------------------------------------------------
 *
 * @generated from message api.tv_fs.v1.GetAppRequest
 */
export class GetAppRequest extends Message<GetAppRequest> {
  /**
   * @generated from field: string mac = 1;
   */
  mac = "";

  /**
   * @generated from field: int64 timestamp = 2;
   */
  timestamp = protoInt64.zero;

  /**
   * @generated from field: string class = 3;
   */
  class = "";

  /**
   * @generated from field: string model_name = 4;
   */
  modelName = "";

  /**
   * @generated from field: string version = 5;
   */
  version = "";

  /**
   * @generated from field: string sign = 6;
   */
  sign = "";

  constructor(data?: PartialMessage<GetAppRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.GetAppRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mac", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "class", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "sign", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAppRequest {
    return new GetAppRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAppRequest {
    return new GetAppRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAppRequest {
    return new GetAppRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAppRequest | PlainMessage<GetAppRequest> | undefined, b: GetAppRequest | PlainMessage<GetAppRequest> | undefined): boolean {
    return proto3.util.equals(GetAppRequest, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.GetFirmwareRequest
 */
export class GetFirmwareRequest extends Message<GetFirmwareRequest> {
  /**
   * @generated from field: string mac = 1;
   */
  mac = "";

  /**
   * @generated from field: int64 timestamp = 2;
   */
  timestamp = protoInt64.zero;

  /**
   * @generated from field: string model_name = 3;
   */
  modelName = "";

  /**
   * @generated from field: string version = 4;
   */
  version = "";

  /**
   * @generated from field: string build_id = 5;
   */
  buildId = "";

  /**
   * @generated from field: string sign = 6;
   */
  sign = "";

  constructor(data?: PartialMessage<GetFirmwareRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.GetFirmwareRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mac", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "build_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "sign", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetFirmwareRequest {
    return new GetFirmwareRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetFirmwareRequest {
    return new GetFirmwareRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetFirmwareRequest {
    return new GetFirmwareRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetFirmwareRequest | PlainMessage<GetFirmwareRequest> | undefined, b: GetFirmwareRequest | PlainMessage<GetFirmwareRequest> | undefined): boolean {
    return proto3.util.equals(GetFirmwareRequest, a, b);
  }
}

/**
 * ------------------------------
 *
 * @generated from message api.tv_fs.v1.GeneralRequest
 */
export class GeneralRequest extends Message<GeneralRequest> {
  /**
   * @generated from field: string mac = 1;
   */
  mac = "";

  /**
   * @generated from field: int64 timestamp = 2;
   */
  timestamp = protoInt64.zero;

  /**
   * @generated from field: string sign = 3;
   */
  sign = "";

  constructor(data?: PartialMessage<GeneralRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.GeneralRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mac", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "sign", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeneralRequest {
    return new GeneralRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeneralRequest {
    return new GeneralRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeneralRequest {
    return new GeneralRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GeneralRequest | PlainMessage<GeneralRequest> | undefined, b: GeneralRequest | PlainMessage<GeneralRequest> | undefined): boolean {
    return proto3.util.equals(GeneralRequest, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.AppWhiteRequest
 */
export class AppWhiteRequest extends Message<AppWhiteRequest> {
  /**
   * @generated from field: string mac = 1;
   */
  mac = "";

  /**
   * @generated from field: int64 timestamp = 2;
   */
  timestamp = protoInt64.zero;

  /**
   * @generated from field: string sign = 3;
   */
  sign = "";

  /**
   * @generated from field: int64 version = 4;
   */
  version = protoInt64.zero;

  constructor(data?: PartialMessage<AppWhiteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.AppWhiteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mac", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "sign", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "version", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AppWhiteRequest {
    return new AppWhiteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AppWhiteRequest {
    return new AppWhiteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AppWhiteRequest {
    return new AppWhiteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AppWhiteRequest | PlainMessage<AppWhiteRequest> | undefined, b: AppWhiteRequest | PlainMessage<AppWhiteRequest> | undefined): boolean {
    return proto3.util.equals(AppWhiteRequest, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.GetApkCategoryRequest
 */
export class GetApkCategoryRequest extends Message<GetApkCategoryRequest> {
  /**
   * @generated from field: string mac = 1;
   */
  mac = "";

  /**
   * @generated from field: int64 timestamp = 2;
   */
  timestamp = protoInt64.zero;

  /**
   * @generated from field: string sign = 3;
   */
  sign = "";

  /**
   * @generated from field: string parent_id = 4;
   */
  parentId = "";

  constructor(data?: PartialMessage<GetApkCategoryRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.GetApkCategoryRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mac", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "sign", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "parent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetApkCategoryRequest {
    return new GetApkCategoryRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetApkCategoryRequest {
    return new GetApkCategoryRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetApkCategoryRequest {
    return new GetApkCategoryRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetApkCategoryRequest | PlainMessage<GetApkCategoryRequest> | undefined, b: GetApkCategoryRequest | PlainMessage<GetApkCategoryRequest> | undefined): boolean {
    return proto3.util.equals(GetApkCategoryRequest, a, b);
  }
}

/**
 * -----------------------------------------------------------
 * 可下载项目记录
 *
 * @generated from message api.tv_fs.v1.DownloadRecord
 */
export class DownloadRecord extends Message<DownloadRecord> {
  /**
   * @generated from field: int64 record_id = 1;
   */
  recordId = protoInt64.zero;

  /**
   * @generated from field: api.tv_fs.v1.MlrStatus status = 2;
   */
  status = MlrStatus.UNSPECIFIED;

  /**
   * 下载文件大小
   *
   * @generated from field: int64 file_size = 3;
   */
  fileSize = protoInt64.zero;

  /**
   * @generated from field: string version = 4;
   */
  version = "";

  /**
   * @generated from field: string apk_type = 5;
   */
  apkType = "";

  /**
   * @generated from field: string media_type = 6;
   */
  mediaType = "";

  /**
   * 下载 URI
   *
   * @generated from field: string media_uri = 7;
   */
  mediaUri = "";

  /**
   * apk 的海报图片
   *
   * @generated from field: string photo_uri = 8;
   */
  photoUri = "";

  /**
   * apk 名称
   *
   * @generated from field: string title = 9;
   */
  title = "";

  /**
   * apk 简介
   *
   * @generated from field: string description = 10;
   */
  description = "";

  /**
   * apk 支持的硬件
   *
   * @generated from field: string hardware = 11;
   */
  hardware = "";

  /**
   * 更新时间
   *
   * @generated from field: string upload_at = 12;
   */
  uploadAt = "";

  /**
   * @generated from field: string md5 = 13;
   */
  md5 = "";

  /**
   * @generated from field: string download_router = 14;
   */
  downloadRouter = "";

  constructor(data?: PartialMessage<DownloadRecord>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.DownloadRecord";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "record_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(MlrStatus) },
    { no: 3, name: "file_size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "apk_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "media_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "media_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "photo_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "hardware", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "upload_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "md5", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "download_router", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadRecord {
    return new DownloadRecord().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadRecord {
    return new DownloadRecord().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadRecord {
    return new DownloadRecord().fromJsonString(jsonString, options);
  }

  static equals(a: DownloadRecord | PlainMessage<DownloadRecord> | undefined, b: DownloadRecord | PlainMessage<DownloadRecord> | undefined): boolean {
    return proto3.util.equals(DownloadRecord, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.UploadMlr
 */
export class UploadMlr extends Message<UploadMlr> {
  /**
   * @generated from field: int64 record_id = 1;
   */
  recordId = protoInt64.zero;

  /**
   * 分销商id
   *
   * @generated from field: int64 distributor_id = 2;
   */
  distributorId = protoInt64.zero;

  /**
   * @generated from field: int64 file_size = 3;
   */
  fileSize = protoInt64.zero;

  /**
   * @generated from field: api.tv_fs.v1.MlrStatus status = 4;
   */
  status = MlrStatus.UNSPECIFIED;

  /**
   * @generated from field: string version = 5;
   */
  version = "";

  /**
   * @generated from field: string apk_type = 6;
   */
  apkType = "";

  /**
   * @generated from field: string media_type = 7;
   */
  mediaType = "";

  /**
   * @generated from field: string media_uri = 8;
   */
  mediaUri = "";

  /**
   * @generated from field: string title = 9;
   */
  title = "";

  /**
   * @generated from field: string description = 10;
   */
  description = "";

  /**
   * @generated from field: string photo_uri = 11;
   */
  photoUri = "";

  /**
   * @generated from field: string hardware = 12;
   */
  hardware = "";

  /**
   * @generated from field: string upload_at = 13;
   */
  uploadAt = "";

  /**
   * @generated from field: string md5 = 14;
   */
  md5 = "";

  constructor(data?: PartialMessage<UploadMlr>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.UploadMlr";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "record_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "distributor_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "file_size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "status", kind: "enum", T: proto3.getEnumType(MlrStatus) },
    { no: 5, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "apk_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "media_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "media_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "photo_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "hardware", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "upload_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "md5", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadMlr {
    return new UploadMlr().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadMlr {
    return new UploadMlr().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadMlr {
    return new UploadMlr().fromJsonString(jsonString, options);
  }

  static equals(a: UploadMlr | PlainMessage<UploadMlr> | undefined, b: UploadMlr | PlainMessage<UploadMlr> | undefined): boolean {
    return proto3.util.equals(UploadMlr, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.ApkFilter
 */
export class ApkFilter extends Message<ApkFilter> {
  /**
   * apk名称
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * 类型
   *
   * @generated from field: string type = 2;
   */
  type = "";

  /**
   * 包名
   *
   * @generated from field: string class = 3;
   */
  class = "";

  /**
   * 是否推送到市场
   *
   * @generated from field: string is_show_on_market = 4;
   */
  isShowOnMarket = "";

  /**
   * 星级
   *
   * @generated from field: int32 star = 5;
   */
  star = 0;

  /**
   * 是否显示轮播图
   *
   * @generated from field: string is_show_banner = 6;
   */
  isShowBanner = "";

  /**
   * 型号id
   *
   * @generated from field: string model_id = 7;
   */
  modelId = "";

  /**
   * 代理商id
   *
   * @generated from field: string distributor_id = 8;
   */
  distributorId = "";

  /**
   * @generated from field: string is_white = 9;
   */
  isWhite = "";

  /**
   * @generated from field: string is_show_tool_tip = 10;
   */
  isShowToolTip = "";

  constructor(data?: PartialMessage<ApkFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.ApkFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "class", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "is_show_on_market", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "star", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "is_show_banner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "is_white", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "is_show_tool_tip", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApkFilter {
    return new ApkFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApkFilter {
    return new ApkFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApkFilter {
    return new ApkFilter().fromJsonString(jsonString, options);
  }

  static equals(a: ApkFilter | PlainMessage<ApkFilter> | undefined, b: ApkFilter | PlainMessage<ApkFilter> | undefined): boolean {
    return proto3.util.equals(ApkFilter, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.ApkCopy
 */
export class ApkCopy extends Message<ApkCopy> {
  /**
   * apk名称
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * 型号id
   *
   * @generated from field: repeated string model_id = 2;
   */
  modelId: string[] = [];

  /**
   * 代理商id
   *
   * @generated from field: string distributor_id = 3;
   */
  distributorId = "";

  constructor(data?: PartialMessage<ApkCopy>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.ApkCopy";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApkCopy {
    return new ApkCopy().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApkCopy {
    return new ApkCopy().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApkCopy {
    return new ApkCopy().fromJsonString(jsonString, options);
  }

  static equals(a: ApkCopy | PlainMessage<ApkCopy> | undefined, b: ApkCopy | PlainMessage<ApkCopy> | undefined): boolean {
    return proto3.util.equals(ApkCopy, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.Apk
 */
export class Apk extends Message<Apk> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * apk名称
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * 类型
   *
   * @generated from field: string type = 3;
   */
  type = "";

  /**
   * 包名
   *
   * @generated from field: string class = 4;
   */
  class = "";

  /**
   * icon图标
   *
   * @generated from field: string img = 5;
   */
  img = "";

  /**
   * 排序
   *
   * @generated from field: int32 sort = 6;
   */
  sort = 0;

  /**
   * 是否推送到市场
   *
   * @generated from field: bool is_show_on_market = 7;
   */
  isShowOnMarket = false;

  /**
   * 型号id
   *
   * @generated from field: string model_id = 8;
   */
  modelId = "";

  /**
   * 星级
   *
   * @generated from field: int32 star = 9;
   */
  star = 0;

  /**
   * 下载次数
   *
   * @generated from field: int32 download_count = 10;
   */
  downloadCount = 0;

  /**
   * 轮播图
   *
   * @generated from field: string banner_img = 11;
   */
  bannerImg = "";

  /**
   * 是否显示轮播图
   *
   * @generated from field: bool is_show_banner = 12;
   */
  isShowBanner = false;

  /**
   * 代理商id
   *
   * @generated from field: string distributor_id = 13;
   */
  distributorId = "";

  /**
   * 创建时间戳
   *
   * @generated from field: int64 created = 14;
   */
  created = protoInt64.zero;

  /**
   * 更新时间戳
   *
   * @generated from field: int64 updated = 15;
   */
  updated = protoInt64.zero;

  /**
   * 是否删除
   *
   * @generated from field: bool deleted = 16;
   */
  deleted = false;

  /**
   * 是否白名单
   *
   * @generated from field: bool is_white = 17;
   */
  isWhite = false;

  /**
   * 文件数量
   *
   * @generated from field: int32 file_num = 18;
   */
  fileNum = 0;

  /**
   * 分销商名称
   *
   * @generated from field: string distributor_name = 19;
   */
  distributorName = "";

  /**
   * 型号名称
   *
   * @generated from field: string model_name = 20;
   */
  modelName = "";

  /**
   * @generated from field: bool is_show_tool_tip = 21;
   */
  isShowToolTip = false;

  /**
   * @generated from field: string parent_category = 22;
   */
  parentCategory = "";

  /**
   * 分类id
   *
   * @generated from field: string category_id = 23;
   */
  categoryId = "";

  /**
   * 分类名称
   *
   * @generated from field: string category_name = 24;
   */
  categoryName = "";

  /**
   * apk 内容
   *
   * @generated from field: string apk_content = 25;
   */
  apkContent = "";

  /**
   * @generated from field: repeated string apk_img = 26;
   */
  apkImg: string[] = [];

  /**
   * @generated from field: string apk_img_str = 27;
   */
  apkImgStr = "";

  /**
   * 是否提示更新
   *
   * @generated from field: bool is_prompt_update = 28;
   */
  isPromptUpdate = false;

  /**
   * @generated from field: string system_content = 29;
   */
  systemContent = "";

  /**
   * @generated from field: string copyright = 30;
   */
  copyright = "";

  constructor(data?: PartialMessage<Apk>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.Apk";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "class", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "img", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "sort", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "is_show_on_market", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "star", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "download_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "banner_img", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "is_show_banner", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 13, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 15, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 16, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 17, name: "is_white", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 18, name: "file_num", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 19, name: "distributor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 20, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 21, name: "is_show_tool_tip", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 22, name: "parent_category", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 23, name: "category_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 24, name: "category_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 25, name: "apk_content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 26, name: "apk_img", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 27, name: "apk_img_str", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 28, name: "is_prompt_update", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 29, name: "system_content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 30, name: "copyright", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Apk {
    return new Apk().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Apk {
    return new Apk().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Apk {
    return new Apk().fromJsonString(jsonString, options);
  }

  static equals(a: Apk | PlainMessage<Apk> | undefined, b: Apk | PlainMessage<Apk> | undefined): boolean {
    return proto3.util.equals(Apk, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.ApkCategory
 */
export class ApkCategory extends Message<ApkCategory> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * 分类名称
   *
   * @generated from field: string category_name = 2;
   */
  categoryName = "";

  /**
   * 排序
   *
   * @generated from field: int32 sort = 3;
   */
  sort = 0;

  /**
   * 创建时间戳
   *
   * @generated from field: int64 created = 4;
   */
  created = protoInt64.zero;

  /**
   * 更新时间戳
   *
   * @generated from field: int64 updated = 5;
   */
  updated = protoInt64.zero;

  /**
   * 是否删除
   *
   * @generated from field: bool deleted = 6;
   */
  deleted = false;

  /**
   * 
   *
   * @generated from field: string parent_id = 7;
   */
  parentId = "";

  constructor(data?: PartialMessage<ApkCategory>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.ApkCategory";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "category_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "sort", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "parent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApkCategory {
    return new ApkCategory().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApkCategory {
    return new ApkCategory().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApkCategory {
    return new ApkCategory().fromJsonString(jsonString, options);
  }

  static equals(a: ApkCategory | PlainMessage<ApkCategory> | undefined, b: ApkCategory | PlainMessage<ApkCategory> | undefined): boolean {
    return proto3.util.equals(ApkCategory, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.ApkDetail
 */
export class ApkDetail extends Message<ApkDetail> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string apk_id = 2;
   */
  apkId = "";

  /**
   * 版本
   *
   * @generated from field: string version = 3;
   */
  version = "";

  /**
   * md5签名
   *
   * @generated from field: string md5 = 4;
   */
  md5 = "";

  /**
   * 地址
   *
   * @generated from field: string url = 5;
   */
  url = "";

  /**
   * 内容
   *
   * @generated from field: string content = 6;
   */
  content = "";

  /**
   * 是否强制更新
   *
   * @generated from field: bool force_update = 7;
   */
  forceUpdate = false;

  /**
   * 存储位置
   *
   * @generated from field: string save_position = 8;
   */
  savePosition = "";

  /**
   * 文件大小
   *
   * @generated from field: int64 filesize = 9;
   */
  filesize = protoInt64.zero;

  /**
   * 创建时间
   *
   * @generated from field: int64 created = 10;
   */
  created = protoInt64.zero;

  /**
   * 更新时间
   *
   * @generated from field: int64 updated = 11;
   */
  updated = protoInt64.zero;

  /**
   * 是否删除
   *
   * @generated from field: bool deleted = 12;
   */
  deleted = false;

  /**
   * @generated from field: bool force_uninstall = 13;
   */
  forceUninstall = false;

  /**
   * @generated from field: bool is_show_tool_tip = 14;
   */
  isShowToolTip = false;

  constructor(data?: PartialMessage<ApkDetail>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.ApkDetail";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "apk_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "md5", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "force_update", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "save_position", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "filesize", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 12, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 13, name: "force_uninstall", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 14, name: "is_show_tool_tip", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApkDetail {
    return new ApkDetail().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApkDetail {
    return new ApkDetail().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApkDetail {
    return new ApkDetail().fromJsonString(jsonString, options);
  }

  static equals(a: ApkDetail | PlainMessage<ApkDetail> | undefined, b: ApkDetail | PlainMessage<ApkDetail> | undefined): boolean {
    return proto3.util.equals(ApkDetail, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.Firmware
 */
export class Firmware extends Message<Firmware> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string model_id = 3;
   */
  modelId = "";

  /**
   * @generated from field: string distributor_id = 4;
   */
  distributorId = "";

  /**
   * @generated from field: int64 created = 5;
   */
  created = protoInt64.zero;

  /**
   * @generated from field: int64 updated = 6;
   */
  updated = protoInt64.zero;

  /**
   * @generated from field: bool deleted = 7;
   */
  deleted = false;

  /**
   * @generated from field: bool is_use = 8;
   */
  isUse = false;

  /**
   * @generated from field: string model_name = 9;
   */
  modelName = "";

  /**
   * @generated from field: string distributor_name = 10;
   */
  distributorName = "";

  constructor(data?: PartialMessage<Firmware>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.Firmware";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "is_use", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "distributor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Firmware {
    return new Firmware().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Firmware {
    return new Firmware().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Firmware {
    return new Firmware().fromJsonString(jsonString, options);
  }

  static equals(a: Firmware | PlainMessage<Firmware> | undefined, b: Firmware | PlainMessage<Firmware> | undefined): boolean {
    return proto3.util.equals(Firmware, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.FirmwareDetail
 */
export class FirmwareDetail extends Message<FirmwareDetail> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string firmware_id = 2;
   */
  firmwareId = "";

  /**
   * @generated from field: string version = 3;
   */
  version = "";

  /**
   * @generated from field: string md5 = 4;
   */
  md5 = "";

  /**
   * @generated from field: string url = 5;
   */
  url = "";

  /**
   * @generated from field: string content = 6;
   */
  content = "";

  /**
   * @generated from field: bool force_update = 7;
   */
  forceUpdate = false;

  /**
   * @generated from field: string save_position = 8;
   */
  savePosition = "";

  /**
   * @generated from field: int64 filesize = 9;
   */
  filesize = protoInt64.zero;

  /**
   * @generated from field: int64 created = 10;
   */
  created = protoInt64.zero;

  /**
   * @generated from field: int64 updated = 11;
   */
  updated = protoInt64.zero;

  /**
   * @generated from field: bool deleted = 12;
   */
  deleted = false;

  /**
   * @generated from field: string build_id = 13;
   */
  buildId = "";

  /**
   * 包类型 1全量 2增量
   *
   * @generated from field: int32 package_type = 14;
   */
  packageType = 0;

  /**
   * 当前版本
   *
   * @generated from field: string current_version = 15;
   */
  currentVersion = "";

  /**
   * r2 key值
   *
   * @generated from field: string r2_key = 16;
   */
  r2Key = "";

  /**
   * 
   *
   * @generated from field: string is_upload = 17;
   */
  isUpload = "";

  constructor(data?: PartialMessage<FirmwareDetail>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.FirmwareDetail";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "firmware_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "md5", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "force_update", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "save_position", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "filesize", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 12, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 13, name: "build_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "package_type", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 15, name: "current_version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "r2_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 17, name: "is_upload", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FirmwareDetail {
    return new FirmwareDetail().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FirmwareDetail {
    return new FirmwareDetail().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FirmwareDetail {
    return new FirmwareDetail().fromJsonString(jsonString, options);
  }

  static equals(a: FirmwareDetail | PlainMessage<FirmwareDetail> | undefined, b: FirmwareDetail | PlainMessage<FirmwareDetail> | undefined): boolean {
    return proto3.util.equals(FirmwareDetail, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.Advertisement
 */
export class Advertisement extends Message<Advertisement> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string play_time = 3;
   */
  playTime = "";

  /**
   * @generated from field: string version = 4;
   */
  version = "";

  /**
   * @generated from field: string md5 = 5;
   */
  md5 = "";

  /**
   * @generated from field: string url = 6;
   */
  url = "";

  /**
   * @generated from field: string content = 7;
   */
  content = "";

  /**
   * @generated from field: int64 filesize = 8;
   */
  filesize = protoInt64.zero;

  /**
   * @generated from field: string distributor_id = 9;
   */
  distributorId = "";

  /**
   * @generated from field: string model_id = 10;
   */
  modelId = "";

  /**
   * @generated from field: int64 created = 11;
   */
  created = protoInt64.zero;

  /**
   * @generated from field: int64 updated = 12;
   */
  updated = protoInt64.zero;

  /**
   * @generated from field: bool deleted = 13;
   */
  deleted = false;

  /**
   * @generated from field: string type = 14;
   */
  type = "";

  /**
   * @generated from field: string model_name = 15;
   */
  modelName = "";

  /**
   * @generated from field: string distributor_name = 16;
   */
  distributorName = "";

  constructor(data?: PartialMessage<Advertisement>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.Advertisement";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "play_time", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "md5", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "filesize", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 12, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 13, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 14, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "distributor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Advertisement {
    return new Advertisement().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Advertisement {
    return new Advertisement().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Advertisement {
    return new Advertisement().fromJsonString(jsonString, options);
  }

  static equals(a: Advertisement | PlainMessage<Advertisement> | undefined, b: Advertisement | PlainMessage<Advertisement> | undefined): boolean {
    return proto3.util.equals(Advertisement, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.AdvertisementPicture
 */
export class AdvertisementPicture extends Message<AdvertisementPicture> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string version = 2;
   */
  version = "";

  /**
   * @generated from field: string md5 = 3;
   */
  md5 = "";

  /**
   * @generated from field: string url = 4;
   */
  url = "";

  /**
   * @generated from field: string content = 5;
   */
  content = "";

  /**
   * @generated from field: int64 filesize = 6;
   */
  filesize = protoInt64.zero;

  /**
   * @generated from field: string distributor_id = 7;
   */
  distributorId = "";

  /**
   * @generated from field: string model_id = 8;
   */
  modelId = "";

  /**
   * @generated from field: int64 created = 9;
   */
  created = protoInt64.zero;

  /**
   * @generated from field: int64 updated = 10;
   */
  updated = protoInt64.zero;

  /**
   * @generated from field: bool deleted = 11;
   */
  deleted = false;

  /**
   * @generated from field: string name = 12;
   */
  name = "";

  /**
   * @generated from field: bool is_use = 13;
   */
  isUse = false;

  /**
   * @generated from field: int32 sort = 14;
   */
  sort = 0;

  /**
   * @generated from field: string model_name = 15;
   */
  modelName = "";

  /**
   * @generated from field: string distributor_name = 16;
   */
  distributorName = "";

  constructor(data?: PartialMessage<AdvertisementPicture>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.AdvertisementPicture";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "md5", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "filesize", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "is_use", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 14, name: "sort", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 15, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "distributor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdvertisementPicture {
    return new AdvertisementPicture().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdvertisementPicture {
    return new AdvertisementPicture().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdvertisementPicture {
    return new AdvertisementPicture().fromJsonString(jsonString, options);
  }

  static equals(a: AdvertisementPicture | PlainMessage<AdvertisementPicture> | undefined, b: AdvertisementPicture | PlainMessage<AdvertisementPicture> | undefined): boolean {
    return proto3.util.equals(AdvertisementPicture, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.HomeBackgroundImage
 */
export class HomeBackgroundImage extends Message<HomeBackgroundImage> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string version = 2;
   */
  version = "";

  /**
   * @generated from field: string md5 = 3;
   */
  md5 = "";

  /**
   * @generated from field: string url = 4;
   */
  url = "";

  /**
   * @generated from field: string content = 5;
   */
  content = "";

  /**
   * @generated from field: int64 filesize = 6;
   */
  filesize = protoInt64.zero;

  /**
   * @generated from field: string distributor_id = 7;
   */
  distributorId = "";

  /**
   * @generated from field: string model_id = 8;
   */
  modelId = "";

  /**
   * @generated from field: bool is_use = 9;
   */
  isUse = false;

  /**
   * @generated from field: int64 created = 10;
   */
  created = protoInt64.zero;

  /**
   * @generated from field: int64 updated = 11;
   */
  updated = protoInt64.zero;

  /**
   * @generated from field: bool deleted = 12;
   */
  deleted = false;

  /**
   * @generated from field: string model_name = 13;
   */
  modelName = "";

  /**
   * @generated from field: string distributor_name = 14;
   */
  distributorName = "";

  /**
   * @generated from field: int32 sort = 15;
   */
  sort = 0;

  constructor(data?: PartialMessage<HomeBackgroundImage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.HomeBackgroundImage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "md5", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "filesize", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "is_use", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 10, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 12, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 13, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "distributor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "sort", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HomeBackgroundImage {
    return new HomeBackgroundImage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HomeBackgroundImage {
    return new HomeBackgroundImage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HomeBackgroundImage {
    return new HomeBackgroundImage().fromJsonString(jsonString, options);
  }

  static equals(a: HomeBackgroundImage | PlainMessage<HomeBackgroundImage> | undefined, b: HomeBackgroundImage | PlainMessage<HomeBackgroundImage> | undefined): boolean {
    return proto3.util.equals(HomeBackgroundImage, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.Notification
 */
export class Notification extends Message<Notification> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string content = 3;
   */
  content = "";

  /**
   * @generated from field: string distributor_id = 4;
   */
  distributorId = "";

  /**
   * @generated from field: string model_id = 5;
   */
  modelId = "";

  /**
   * @generated from field: bool is_use = 6;
   */
  isUse = false;

  /**
   * @generated from field: int64 created = 7;
   */
  created = protoInt64.zero;

  /**
   * @generated from field: int64 updated = 8;
   */
  updated = protoInt64.zero;

  /**
   * @generated from field: bool deleted = 9;
   */
  deleted = false;

  /**
   * @generated from field: string model_name = 10;
   */
  modelName = "";

  /**
   * @generated from field: string distributor_name = 11;
   */
  distributorName = "";

  constructor(data?: PartialMessage<Notification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.Notification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "is_use", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 10, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "distributor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Notification {
    return new Notification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Notification {
    return new Notification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Notification {
    return new Notification().fromJsonString(jsonString, options);
  }

  static equals(a: Notification | PlainMessage<Notification> | undefined, b: Notification | PlainMessage<Notification> | undefined): boolean {
    return proto3.util.equals(Notification, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.DistributorDetail
 */
export class DistributorDetail extends Message<DistributorDetail> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string distributor_id = 4;
   */
  distributorId = "";

  /**
   * @generated from field: string model_id = 5;
   */
  modelId = "";

  /**
   * @generated from field: string facebook = 6;
   */
  facebook = "";

  /**
   * @generated from field: string facebook_img = 7;
   */
  facebookImg = "";

  /**
   * @generated from field: string email = 8;
   */
  email = "";

  /**
   * @generated from field: string email_img = 9;
   */
  emailImg = "";

  /**
   * @generated from field: int64 created = 10;
   */
  created = protoInt64.zero;

  /**
   * @generated from field: int64 updated = 11;
   */
  updated = protoInt64.zero;

  /**
   * @generated from field: bool deleted = 12;
   */
  deleted = false;

  /**
   * @generated from field: string model_name = 13;
   */
  modelName = "";

  /**
   * @generated from field: string distributor_name = 14;
   */
  distributorName = "";

  constructor(data?: PartialMessage<DistributorDetail>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.DistributorDetail";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "facebook", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "facebook_img", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "email_img", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 12, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 13, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "distributor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DistributorDetail {
    return new DistributorDetail().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DistributorDetail {
    return new DistributorDetail().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DistributorDetail {
    return new DistributorDetail().fromJsonString(jsonString, options);
  }

  static equals(a: DistributorDetail | PlainMessage<DistributorDetail> | undefined, b: DistributorDetail | PlainMessage<DistributorDetail> | undefined): boolean {
    return proto3.util.equals(DistributorDetail, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.ApkInfo
 */
export class ApkInfo extends Message<ApkInfo> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * apk名称
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * 类型
   *
   * @generated from field: string type = 3;
   */
  type = "";

  /**
   * 包名
   *
   * @generated from field: string class = 4;
   */
  class = "";

  /**
   * icon图标
   *
   * @generated from field: string img = 5;
   */
  img = "";

  /**
   * 排序
   *
   * @generated from field: int32 sort = 6;
   */
  sort = 0;

  /**
   * 是否推送到市场
   *
   * @generated from field: bool is_show_on_market = 7;
   */
  isShowOnMarket = false;

  /**
   * 星级
   *
   * @generated from field: int32 star = 8;
   */
  star = 0;

  /**
   * 下载次数
   *
   * @generated from field: int32 download_count = 9;
   */
  downloadCount = 0;

  /**
   * 轮播图
   *
   * @generated from field: string banner_img = 10;
   */
  bannerImg = "";

  /**
   * 是否显示轮播图
   *
   * @generated from field: bool is_show_banner = 11;
   */
  isShowBanner = false;

  /**
   * @generated from field: string apk_id = 12;
   */
  apkId = "";

  /**
   * 版本
   *
   * @generated from field: string version = 13;
   */
  version = "";

  /**
   * md5签名
   *
   * @generated from field: string md5 = 14;
   */
  md5 = "";

  /**
   * 地址
   *
   * @generated from field: string url = 15;
   */
  url = "";

  /**
   * 内容
   *
   * @generated from field: string content = 16;
   */
  content = "";

  /**
   * 是否强制更新
   *
   * @generated from field: bool force_update = 17;
   */
  forceUpdate = false;

  /**
   * 存储位置
   *
   * @generated from field: string save_position = 18;
   */
  savePosition = "";

  /**
   * 文件大小
   *
   * @generated from field: int64 filesize = 19;
   */
  filesize = protoInt64.zero;

  /**
   * 更新时间
   *
   * @generated from field: int64 updated = 20;
   */
  updated = protoInt64.zero;

  /**
   * apk分类
   *
   * @generated from field: string category_name = 21;
   */
  categoryName = "";

  /**
   * apk 内容
   *
   * @generated from field: string apk_content = 22;
   */
  apkContent = "";

  /**
   * @generated from field: repeated string apk_img = 23;
   */
  apkImg: string[] = [];

  /**
   * 系统需求
   *
   * @generated from field: string system_content = 24;
   */
  systemContent = "";

  /**
   * apk_img版本
   *
   * @generated from field: string apk_img_version = 25;
   */
  apkImgVersion = "";

  /**
   * 版权信息
   *
   * @generated from field: string copyright = 26;
   */
  copyright = "";

  constructor(data?: PartialMessage<ApkInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.ApkInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "class", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "img", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "sort", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "is_show_on_market", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "star", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "download_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "banner_img", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "is_show_banner", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "apk_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "md5", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 17, name: "force_update", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 18, name: "save_position", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 19, name: "filesize", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 20, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 21, name: "category_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 22, name: "apk_content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 23, name: "apk_img", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 24, name: "system_content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 25, name: "apk_img_version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 26, name: "copyright", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApkInfo {
    return new ApkInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApkInfo {
    return new ApkInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApkInfo {
    return new ApkInfo().fromJsonString(jsonString, options);
  }

  static equals(a: ApkInfo | PlainMessage<ApkInfo> | undefined, b: ApkInfo | PlainMessage<ApkInfo> | undefined): boolean {
    return proto3.util.equals(ApkInfo, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.AppWhiteList
 */
export class AppWhiteList extends Message<AppWhiteList> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string distributor_id = 2;
   */
  distributorId = "";

  /**
   * @generated from field: string model_id = 3;
   */
  modelId = "";

  /**
   * @generated from field: string class = 4;
   */
  class = "";

  /**
   * @generated from field: bool is_use = 5;
   */
  isUse = false;

  /**
   * @generated from field: int32 created = 6;
   */
  created = 0;

  /**
   * @generated from field: int32 updated = 7;
   */
  updated = 0;

  constructor(data?: PartialMessage<AppWhiteList>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.AppWhiteList";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "class", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "is_use", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "created", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "updated", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AppWhiteList {
    return new AppWhiteList().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AppWhiteList {
    return new AppWhiteList().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AppWhiteList {
    return new AppWhiteList().fromJsonString(jsonString, options);
  }

  static equals(a: AppWhiteList | PlainMessage<AppWhiteList> | undefined, b: AppWhiteList | PlainMessage<AppWhiteList> | undefined): boolean {
    return proto3.util.equals(AppWhiteList, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.ProvideTemplate
 */
export class ProvideTemplate extends Message<ProvideTemplate> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * @generated from field: string distributor_id = 2;
   */
  distributorId = "";

  /**
   * @generated from field: string model_id = 3;
   */
  modelId = "";

  /**
   * @generated from field: string alias_name = 4;
   */
  aliasName = "";

  /**
   * @generated from field: string description_store = 5;
   */
  descriptionStore = "";

  /**
   * @generated from field: string description_add_pic = 6;
   */
  descriptionAddPic = "";

  /**
   * @generated from field: string distributor_name = 7;
   */
  distributorName = "";

  /**
   * @generated from field: string model_name = 8;
   */
  modelName = "";

  constructor(data?: PartialMessage<ProvideTemplate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.ProvideTemplate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "alias_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "description_store", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "description_add_pic", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "distributor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProvideTemplate {
    return new ProvideTemplate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProvideTemplate {
    return new ProvideTemplate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProvideTemplate {
    return new ProvideTemplate().fromJsonString(jsonString, options);
  }

  static equals(a: ProvideTemplate | PlainMessage<ProvideTemplate> | undefined, b: ProvideTemplate | PlainMessage<ProvideTemplate> | undefined): boolean {
    return proto3.util.equals(ProvideTemplate, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.AppBanner
 */
export class AppBanner extends Message<AppBanner> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string version = 2;
   */
  version = "";

  /**
   * @generated from field: string md5 = 3;
   */
  md5 = "";

  /**
   * @generated from field: string url = 4;
   */
  url = "";

  /**
   * @generated from field: string content = 5;
   */
  content = "";

  /**
   * @generated from field: int64 filesize = 6;
   */
  filesize = protoInt64.zero;

  /**
   * @generated from field: string distributor_id = 7;
   */
  distributorId = "";

  /**
   * @generated from field: string model_id = 8;
   */
  modelId = "";

  /**
   * @generated from field: int64 created = 9;
   */
  created = protoInt64.zero;

  /**
   * @generated from field: int64 updated = 10;
   */
  updated = protoInt64.zero;

  /**
   * @generated from field: bool deleted = 11;
   */
  deleted = false;

  /**
   * @generated from field: string name = 12;
   */
  name = "";

  /**
   * @generated from field: bool is_use = 13;
   */
  isUse = false;

  /**
   * @generated from field: int32 sort = 14;
   */
  sort = 0;

  /**
   * @generated from field: string model_name = 15;
   */
  modelName = "";

  /**
   * @generated from field: string distributor_name = 16;
   */
  distributorName = "";

  constructor(data?: PartialMessage<AppBanner>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.AppBanner";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "md5", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "filesize", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "created", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "updated", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "is_use", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 14, name: "sort", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 15, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "distributor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AppBanner {
    return new AppBanner().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AppBanner {
    return new AppBanner().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AppBanner {
    return new AppBanner().fromJsonString(jsonString, options);
  }

  static equals(a: AppBanner | PlainMessage<AppBanner> | undefined, b: AppBanner | PlainMessage<AppBanner> | undefined): boolean {
    return proto3.util.equals(AppBanner, a, b);
  }
}

/**
 * app推荐
 *
 * @generated from message api.tv_fs.v1.RecommendApk
 */
export class RecommendApk extends Message<RecommendApk> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * 图片
   *
   * @generated from field: string img = 2;
   */
  img = "";

  /**
   * 包名
   *
   * @generated from field: string package_name = 3;
   */
  packageName = "";

  /**
   * 名称
   *
   * @generated from field: string app_name = 4;
   */
  appName = "";

  /**
   * 排序
   *
   * @generated from field: int32 sort = 5;
   */
  sort = 0;

  /**
   * int32 class_id = 6;//选项id
   *
   * 语言
   *
   * @generated from field: string lang = 6;
   */
  lang = "";

  /**
   * string class_name = 8;//选项
   *
   * 更新时间
   *
   * @generated from field: string update_at = 7;
   */
  updateAt = "";

  /**
   * 是否删除 false 未删除 true 已删除
   *
   * @generated from field: bool deleted = 8;
   */
  deleted = false;

  /**
   * @generated from field: string distributor_id = 9;
   */
  distributorId = "";

  /**
   * @generated from field: string model_id = 10;
   */
  modelId = "";

  constructor(data?: PartialMessage<RecommendApk>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.RecommendApk";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "img", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "package_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "app_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "sort", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "lang", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "update_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecommendApk {
    return new RecommendApk().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecommendApk {
    return new RecommendApk().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecommendApk {
    return new RecommendApk().fromJsonString(jsonString, options);
  }

  static equals(a: RecommendApk | PlainMessage<RecommendApk> | undefined, b: RecommendApk | PlainMessage<RecommendApk> | undefined): boolean {
    return proto3.util.equals(RecommendApk, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.DistributorModelList
 */
export class DistributorModelList extends Message<DistributorModelList> {
  /**
   * @generated from field: string distributor_id = 1;
   */
  distributorId = "";

  /**
   * @generated from field: repeated string model_id = 2;
   */
  modelId: string[] = [];

  constructor(data?: PartialMessage<DistributorModelList>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.DistributorModelList";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "distributor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DistributorModelList {
    return new DistributorModelList().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DistributorModelList {
    return new DistributorModelList().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DistributorModelList {
    return new DistributorModelList().fromJsonString(jsonString, options);
  }

  static equals(a: DistributorModelList | PlainMessage<DistributorModelList> | undefined, b: DistributorModelList | PlainMessage<DistributorModelList> | undefined): boolean {
    return proto3.util.equals(DistributorModelList, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.RecommendsRequest
 */
export class RecommendsRequest extends Message<RecommendsRequest> {
  /**
   * @generated from field: string mac = 1;
   */
  mac = "";

  /**
   * @generated from field: int64 timestamp = 2;
   */
  timestamp = protoInt64.zero;

  /**
   * @generated from field: string class = 3;
   */
  class = "";

  /**
   * @generated from field: string lang = 4;
   */
  lang = "";

  /**
   * @generated from field: string sign = 5;
   */
  sign = "";

  /**
   * @generated from field: string model_name = 6;
   */
  modelName = "";

  constructor(data?: PartialMessage<RecommendsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.RecommendsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mac", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "class", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "lang", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "sign", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecommendsRequest {
    return new RecommendsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecommendsRequest {
    return new RecommendsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecommendsRequest {
    return new RecommendsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RecommendsRequest | PlainMessage<RecommendsRequest> | undefined, b: RecommendsRequest | PlainMessage<RecommendsRequest> | undefined): boolean {
    return proto3.util.equals(RecommendsRequest, a, b);
  }
}

/**
 * @generated from message api.tv_fs.v1.ApkVersion
 */
export class ApkVersion extends Message<ApkVersion> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string class_name = 2;
   */
  className = "";

  /**
   * @generated from field: string version = 3;
   */
  version = "";

  /**
   * @generated from field: string content = 4;
   */
  content = "";

  /**
   * @generated from field: string icon = 5;
   */
  icon = "";

  constructor(data?: PartialMessage<ApkVersion>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.tv_fs.v1.ApkVersion";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "class_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "icon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApkVersion {
    return new ApkVersion().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApkVersion {
    return new ApkVersion().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApkVersion {
    return new ApkVersion().fromJsonString(jsonString, options);
  }

  static equals(a: ApkVersion | PlainMessage<ApkVersion> | undefined, b: ApkVersion | PlainMessage<ApkVersion> | undefined): boolean {
    return proto3.util.equals(ApkVersion, a, b);
  }
}

