// as 服务, 即是 a3 的 grpc 服务

// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file api/ps/v1/ps.proto (package api.ps.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CountDistributorRequest, CountDistributorResponse, CountLotByDistributorRequest, CountLotByDistributorResponse, CountLotRequest, CountLotResponse, CountMacSerialRequest, CountMacSerialResponse, CountMacSerialSettingRequest, CountMacSerialSettingResponse, QueryDistributorListRequest, QueryDistributorListResponse, QueryLotListByDistributorRequest, QueryLotListByDistributorResponse, QueryLotListRequest, QueryLotListResponse, QueryMacSerialListRequest, QueryMacSerialListResponse, QueryMacSerialSettingListRequest, QueryMacSerialSettingListResponse, UpsertDistributorListRequest, UpsertDistributorListResponse, UpsertLotRequest, UpsertLotResponse, UpsertMacSerialSettingRequest, UpsertMacSerialSettingResponse } from "./ps_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.ps.v1.PService
 */
export const PService = {
  typeName: "api.ps.v1.PService",
  methods: {
    /**
     *  rpc Ping(PingRequest) returns (PingResponse);
     * ----------------------------------------------------------------------------------------------------------------------
     * 以下是管理界面使用的
     * ----------------------------------------------------------------------------------------------------------------------
     * 分销商与生产批次
     *
     * 批量创建或更新分销商
     *
     * @generated from rpc api.ps.v1.PService.UpsertDistributorList
     */
    upsertDistributorList: {
      name: "UpsertDistributorList",
      I: UpsertDistributorListRequest,
      O: UpsertDistributorListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 统计分销商数量
     *
     * @generated from rpc api.ps.v1.PService.CountDistributor
     */
    countDistributor: {
      name: "CountDistributor",
      I: CountDistributorRequest,
      O: CountDistributorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 查询分销商列表, 分页
     *
     * @generated from rpc api.ps.v1.PService.QueryDistributorList
     */
    queryDistributorList: {
      name: "QueryDistributorList",
      I: QueryDistributorListRequest,
      O: QueryDistributorListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * lot 生产批次
     *
     * 批量创建或更新批次
     *
     * @generated from rpc api.ps.v1.PService.UpsertLot
     */
    upsertLot: {
      name: "UpsertLot",
      I: UpsertLotRequest,
      O: UpsertLotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 统计批次数量
     *
     * @generated from rpc api.ps.v1.PService.CountLot
     */
    countLot: {
      name: "CountLot",
      I: CountLotRequest,
      O: CountLotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 查询批次列表, 分页
     *
     * @generated from rpc api.ps.v1.PService.QueryLotList
     */
    queryLotList: {
      name: "QueryLotList",
      I: QueryLotListRequest,
      O: QueryLotListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 统计分销商的批次数量
     *
     * @generated from rpc api.ps.v1.PService.CountLotByDistributor
     */
    countLotByDistributor: {
      name: "CountLotByDistributor",
      I: CountLotByDistributorRequest,
      O: CountLotByDistributorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 查询分销商的批次列表, 分页
     *
     * @generated from rpc api.ps.v1.PService.QueryLotListByDistributor
     */
    queryLotListByDistributor: {
      name: "QueryLotListByDistributor",
      I: QueryLotListByDistributorRequest,
      O: QueryLotListByDistributorResponse,
      kind: MethodKind.Unary,
    },
    /**
     *  mac 地址与序列号生成设置
     *
     * 创建或更新 mac 地址与序列号生成设置
     *
     * @generated from rpc api.ps.v1.PService.UpsertMacSerialSetting
     */
    upsertMacSerialSetting: {
      name: "UpsertMacSerialSetting",
      I: UpsertMacSerialSettingRequest,
      O: UpsertMacSerialSettingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 统计 mac 地址与序列号生成设置数量
     *
     * @generated from rpc api.ps.v1.PService.CountMacSerialSetting
     */
    countMacSerialSetting: {
      name: "CountMacSerialSetting",
      I: CountMacSerialSettingRequest,
      O: CountMacSerialSettingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 查询 mac 地址与序列号生成设置列表, 分页
     *
     * @generated from rpc api.ps.v1.PService.QueryMacSerialSettingList
     */
    queryMacSerialSettingList: {
      name: "QueryMacSerialSettingList",
      I: QueryMacSerialSettingListRequest,
      O: QueryMacSerialSettingListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 成生的序列号与mac
     *
     * 统计 mac 地址与序列号生成设置数量
     *
     * @generated from rpc api.ps.v1.PService.CountMacSerial
     */
    countMacSerial: {
      name: "CountMacSerial",
      I: CountMacSerialRequest,
      O: CountMacSerialResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 查询 mac 地址与序列号生成设置列表, 分页
     *
     * @generated from rpc api.ps.v1.PService.QueryMacSerialList
     */
    queryMacSerialList: {
      name: "QueryMacSerialList",
      I: QueryMacSerialListRequest,
      O: QueryMacSerialListResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

