// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file api/ws/v1/ws.proto (package api.ws.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
    AuthAccountRequest,
    AuthAccountResponse,
    CopyAppsRequest,
    CopyAppsResponse,
    GetAppDownloadUrlRequest,
    GetAppDownloadUrlResponse,
    GetAppsByCategoriesRequest,
    GetAppsByCategoriesResponse,
    GetAppsByClassRequest,
    GetAppsByClassResponse,
    GetAppsCategoriesRequest,
    GetAppsCategoriesResponse,
    InsertAppsRequest,
    InsertAppsResponse,
    InsertAppsVersionRequest,
    InsertAppsVersionResponse,
    InsertAppUserRequest,
    InsertAppUserResponse,
    InsertCategoriesRequest,
    InsertCategoriesResponse,
    InsertPricePlansRequest,
    InsertPricePlansResponse,
    LoginRequest,
    LoginResponse,
    QueryAllCategoriesRequest,
    QueryAllCategoriesResponse,
    QueryAllPricePlanRequest,
    QueryAllPricePlanResponse,
    QueryAppsListRequest,
    QueryAppsListResponse,
    QueryAppsNewestVersionRequest,
    QueryAppsNewestVersionResponse,
    QueryAppsRequest,
    QueryAppsResponse,
    QueryAppsVersionListRequest,
    QueryAppsVersionListResponse,
    QueryAppUserListRequest,
    QueryAppUserListResponse,
    QueryCategoriesListRequest,
    QueryCategoriesListResponse,
    QueryPricePlansListRequest,
    QueryPricePlansListResponse,
    UpdateAppsRequest,
    UpdateAppsResponse,
    UpdateAppsVersionRequest,
    UpdateAppsVersionResponse,
    UpdateAppUserRequest,
    UpdateAppUserResponse,
    UpdateCategoriesRequest,
    UpdateCategoriesResponse,
    UpdatePricePlansRequest,
    UpdatePricePlansResponse,
    UpdateSelfRequest,
    UpdateSelfResponse,
} from "./ws_pb.ts";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service api.ws.v1.WService
 */
export const WService = {
    typeName: "api.ws.v1.WService",
    methods: {
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.InsertApps
         */
        insertApps: {
            name: "InsertApps",
            I: InsertAppsRequest,
            O: InsertAppsResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.UpdateApps
         */
        updateApps: {
            name: "UpdateApps",
            I: UpdateAppsRequest,
            O: UpdateAppsResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.CopyApps
         */
        copyApps: {
            name: "CopyApps",
            I: CopyAppsRequest,
            O: CopyAppsResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.QueryAppsList
         */
        queryAppsList: {
            name: "QueryAppsList",
            I: QueryAppsListRequest,
            O: QueryAppsListResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.InsertAppsVersion
         */
        insertAppsVersion: {
            name: "InsertAppsVersion",
            I: InsertAppsVersionRequest,
            O: InsertAppsVersionResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.UpdateAppsVersion
         */
        updateAppsVersion: {
            name: "UpdateAppsVersion",
            I: UpdateAppsVersionRequest,
            O: UpdateAppsVersionResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.QueryAppsVersionList
         */
        queryAppsVersionList: {
            name: "QueryAppsVersionList",
            I: QueryAppsVersionListRequest,
            O: QueryAppsVersionListResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.InsertCategories
         */
        insertCategories: {
            name: "InsertCategories",
            I: InsertCategoriesRequest,
            O: InsertCategoriesResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.UpdateCategories
         */
        updateCategories: {
            name: "UpdateCategories",
            I: UpdateCategoriesRequest,
            O: UpdateCategoriesResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.QueryCategoriesList
         */
        queryCategoriesList: {
            name: "QueryCategoriesList",
            I: QueryCategoriesListRequest,
            O: QueryCategoriesListResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.InsertPricePlans
         */
        insertPricePlans: {
            name: "InsertPricePlans",
            I: InsertPricePlansRequest,
            O: InsertPricePlansResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.UpdatePricePlans
         */
        updatePricePlans: {
            name: "UpdatePricePlans",
            I: UpdatePricePlansRequest,
            O: UpdatePricePlansResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.QueryPricePlansList
         */
        queryPricePlansList: {
            name: "QueryPricePlansList",
            I: QueryPricePlansListRequest,
            O: QueryPricePlansListResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.QueryAllCategories
         */
        queryAllCategories: {
            name: "QueryAllCategories",
            I: QueryAllCategoriesRequest,
            O: QueryAllCategoriesResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.QueryAllPricePlan
         */
        queryAllPricePlan: {
            name: "QueryAllPricePlan",
            I: QueryAllPricePlanRequest,
            O: QueryAllPricePlanResponse,
            kind: MethodKind.Unary,
        },
        /**
         *  新增AppUser
         *
         * ui//
         *
         * @generated from rpc api.ws.v1.WService.InsertAppUser
         */
        insertAppUser: {
            name: "InsertAppUser",
            I: InsertAppUserRequest,
            O: InsertAppUserResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.UpdateAppUser
         */
        updateAppUser: {
            name: "UpdateAppUser",
            I: UpdateAppUserRequest,
            O: UpdateAppUserResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.QueryAppUserList
         */
        queryAppUserList: {
            name: "QueryAppUserList",
            I: QueryAppUserListRequest,
            O: QueryAppUserListResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ----------------------------------------盒子端调用--------------------------------------
         *
         * ui
         *
         * @generated from rpc api.ws.v1.WService.QueryApps
         */
        queryApps: {
            name: "QueryApps",
            I: QueryAppsRequest,
            O: QueryAppsResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.GetAppsCategories
         */
        getAppsCategories: {
            name: "GetAppsCategories",
            I: GetAppsCategoriesRequest,
            O: GetAppsCategoriesResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.GetAppsByCategories
         */
        getAppsByCategories: {
            name: "GetAppsByCategories",
            I: GetAppsByCategoriesRequest,
            O: GetAppsByCategoriesResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.GetAppsByClass
         */
        getAppsByClass: {
            name: "GetAppsByClass",
            I: GetAppsByClassRequest,
            O: GetAppsByClassResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.QueryAppsNewestVersion
         */
        queryAppsNewestVersion: {
            name: "QueryAppsNewestVersion",
            I: QueryAppsNewestVersionRequest,
            O: QueryAppsNewestVersionResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.UpdateSelf
         */
        updateSelf: {
            name: "UpdateSelf",
            I: UpdateSelfRequest,
            O: UpdateSelfResponse,
            kind: MethodKind.Unary,
        },
        /**
         *  校验账号
         *
         * ui
         *
         * @generated from rpc api.ws.v1.WService.Login
         */
        login: {
            name: "Login",
            I: LoginRequest,
            O: LoginResponse,
            kind: MethodKind.Unary,
        },
        /**
         * ui
         *
         * @generated from rpc api.ws.v1.WService.AuthAccount
         */
        authAccount: {
            name: "AuthAccount",
            I: AuthAccountRequest,
            O: AuthAccountResponse,
            kind: MethodKind.Unary,
        },
        /**
         *  根据appId获取对应的URl
         *
         * ui
         *
         * @generated from rpc api.ws.v1.WService.GetAppDownloadUrl
         */
        getAppDownloadUrl: {
            name: "GetAppDownloadUrl",
            I: GetAppDownloadUrlRequest,
            O: GetAppDownloadUrlResponse,
            kind: MethodKind.Unary,
        },
    },
} as const;
