// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file api/ta/v1/tas.proto (package api.ta.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BindDistributorModelRequest, BindDistributorModelResponse, DeleteDownloadConfigRequest, DeleteDownloadConfigResponse, DeleteVideoRequest, DeleteVideoResponse, GetAgreementRequest, GetAgreementResponse, GetRecommendsRequest, GetRecommendsResponse, GetSearchRequest, GetSearchResponse, GetVideoRequest, GetVideoResponse, GetVideosByCategoryRequest, GetVideosByCategoryResponse, InsertAgreementRequest, InsertAgreementResponse, InsertClassRequest, InsertClassResponse, InsertDownloadConfigRequest, InsertDownloadConfigResponse, InsertRecommendApkRequest, InsertRecommendApkResponse, InsertVideoRequest, InsertVideoResponse, ParseYoutubeRequest, ParseYoutubeResponse, QueryAgreementListRequest, QueryAgreementListResponse, QueryAllCategoryRequest, QueryAllCategoryResponse, QueryAllClassRequest, QueryAllClassResponse, QueryBindDistributorModelRequest, QueryBindDistributorModelResponse, QueryCategoryListRequest, QueryCategoryListResponse, QueryClassListRequest, QueryClassListResponse, QueryDownloadConfigListRequest, QueryDownloadConfigListResponse, QueryRecommendApkListRequest, QueryRecommendApkListResponse, QueryRegionListRequest, QueryRegionListResponse, QueryVideoListRequest, QueryVideoListResponse, UpdateAgreementRequest, UpdateAgreementResponse, UpdateClassRequest, UpdateClassResponse, UpdateDownloadConfigRequest, UpdateDownloadConfigResponse, UpdateRecommendApkRequest, UpdateRecommendApkResponse, UpdateVideoRequest, UpdateVideoResponse } from "./tas_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.ta.v1.TAService
 */
export const TAService = {
  typeName: "api.ta.v1.TAService",
  methods: {
    /**
     * @generated from rpc api.ta.v1.TAService.QueryAgreementList
     */
    queryAgreementList: {
      name: "QueryAgreementList",
      I: QueryAgreementListRequest,
      O: QueryAgreementListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.InsertAgreement
     */
    insertAgreement: {
      name: "InsertAgreement",
      I: InsertAgreementRequest,
      O: InsertAgreementResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.UpdateAgreement
     */
    updateAgreement: {
      name: "UpdateAgreement",
      I: UpdateAgreementRequest,
      O: UpdateAgreementResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.QueryClassList
     */
    queryClassList: {
      name: "QueryClassList",
      I: QueryClassListRequest,
      O: QueryClassListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.InsertClass
     */
    insertClass: {
      name: "InsertClass",
      I: InsertClassRequest,
      O: InsertClassResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.UpdateClass
     */
    updateClass: {
      name: "UpdateClass",
      I: UpdateClassRequest,
      O: UpdateClassResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.QueryAllClass
     */
    queryAllClass: {
      name: "QueryAllClass",
      I: QueryAllClassRequest,
      O: QueryAllClassResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.QueryAllCategory
     */
    queryAllCategory: {
      name: "QueryAllCategory",
      I: QueryAllCategoryRequest,
      O: QueryAllCategoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.QueryCategoryList
     */
    queryCategoryList: {
      name: "QueryCategoryList",
      I: QueryCategoryListRequest,
      O: QueryCategoryListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.QueryRegionList
     */
    queryRegionList: {
      name: "QueryRegionList",
      I: QueryRegionListRequest,
      O: QueryRegionListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.QueryRecommendApkList
     */
    queryRecommendApkList: {
      name: "QueryRecommendApkList",
      I: QueryRecommendApkListRequest,
      O: QueryRecommendApkListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.InsertRecommendApk
     */
    insertRecommendApk: {
      name: "InsertRecommendApk",
      I: InsertRecommendApkRequest,
      O: InsertRecommendApkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.UpdateRecommendApk
     */
    updateRecommendApk: {
      name: "UpdateRecommendApk",
      I: UpdateRecommendApkRequest,
      O: UpdateRecommendApkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.QueryVideoList
     */
    queryVideoList: {
      name: "QueryVideoList",
      I: QueryVideoListRequest,
      O: QueryVideoListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.InsertVideo
     */
    insertVideo: {
      name: "InsertVideo",
      I: InsertVideoRequest,
      O: InsertVideoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.UpdateVideo
     */
    updateVideo: {
      name: "UpdateVideo",
      I: UpdateVideoRequest,
      O: UpdateVideoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.DeleteVideo
     */
    deleteVideo: {
      name: "DeleteVideo",
      I: DeleteVideoRequest,
      O: DeleteVideoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.QueryDownloadConfigList
     */
    queryDownloadConfigList: {
      name: "QueryDownloadConfigList",
      I: QueryDownloadConfigListRequest,
      O: QueryDownloadConfigListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.InsertDownloadConfig
     */
    insertDownloadConfig: {
      name: "InsertDownloadConfig",
      I: InsertDownloadConfigRequest,
      O: InsertDownloadConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.UpdateDownloadConfig
     */
    updateDownloadConfig: {
      name: "UpdateDownloadConfig",
      I: UpdateDownloadConfigRequest,
      O: UpdateDownloadConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.DeleteDownloadConfig
     */
    deleteDownloadConfig: {
      name: "DeleteDownloadConfig",
      I: DeleteDownloadConfigRequest,
      O: DeleteDownloadConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.ParseYoutube
     */
    parseYoutube: {
      name: "ParseYoutube",
      I: ParseYoutubeRequest,
      O: ParseYoutubeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.QueryBindDistributorModel
     */
    queryBindDistributorModel: {
      name: "QueryBindDistributorModel",
      I: QueryBindDistributorModelRequest,
      O: QueryBindDistributorModelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.BindDistributorModel
     */
    bindDistributorModel: {
      name: "BindDistributorModel",
      I: BindDistributorModelRequest,
      O: BindDistributorModelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ----------------------------------------盒子端调用--------------------------------------
     *
     * @generated from rpc api.ta.v1.TAService.GetRecommends
     */
    getRecommends: {
      name: "GetRecommends",
      I: GetRecommendsRequest,
      O: GetRecommendsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.GetVideo
     */
    getVideo: {
      name: "GetVideo",
      I: GetVideoRequest,
      O: GetVideoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.GetSearch
     */
    getSearch: {
      name: "GetSearch",
      I: GetSearchRequest,
      O: GetSearchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.GetAgreement
     */
    getAgreement: {
      name: "GetAgreement",
      I: GetAgreementRequest,
      O: GetAgreementResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.ta.v1.TAService.GetVideosByCategory
     */
    getVideosByCategory: {
      name: "GetVideosByCategory",
      I: GetVideosByCategoryRequest,
      O: GetVideosByCategoryResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

